name: Notify Discord on New Blog Post (Python)

on:
  push:
    branches:
      - main
    paths:
      - 'src/assets/blog/**.md' # 監視対象のパス

jobs:
  notify_discord_on_new_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # 変更されたファイルを特定するために必要

      - name: Get added markdown files
        id: added_files_check
        uses: tj-actions/changed-files@v44 # 最新バージョンを確認してください
        with:
          files: src/assets/blog/**.md 
          # outputs.added_files で追加されたファイルのリストがスペース区切りで提供されます

      - name: Set up Python
        # 追加された .md ファイルがある場合のみPython環境をセットアップ
        if: steps.added_files_check.outputs.added_files_count > 0
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # プロジェクトに合わせたPythonバージョンを指定

      - name: Install Python dependencies
        if: steps.added_files_check.outputs.added_files_count > 0
        run: |
          python -m pip install --upgrade pip
          pip install python-frontmatter requests
          # もし requirements.txt を使う場合:
          # pip install -r .github/scripts/requirements.txt

      - name: Run Discord notification script for each new post
        # 追加された .md ファイルがあり、かつWebhook URLが設定されている場合のみ実行
        if: steps.added_files_check.outputs.added_files_count > 0 && env.DISCORD_WEBHOOK_URL != ''
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          # スペース区切りの追加されたファイルパスのリスト
          ADDED_FILES_LIST: ${{ steps.added_files_check.outputs.added_files }}
        run: |
          echo "Webhook URL Set: ${{ env.DISCORD_WEBHOOK_URL != '' }}"
          echo "Added files to process: $ADDED_FILES_LIST"
          
          # Pythonスクリプトのパス。リポジトリのルートからの相対パス。
          SCRIPT_PATH=".github/scripts/discord_notify.py"

          if [ ! -f "$SCRIPT_PATH" ]; then
            echo "Error: Python script not found at $SCRIPT_PATH"
            exit 1
          fi

          for file_path in $ADDED_FILES_LIST; do
            echo "Processing file: $file_path"
            # Pythonスクリプトにファイルパスを引数として渡して実行
            python "$SCRIPT_PATH" "$file_path"
            
            # 複数の投稿があった場合にAPIリミットに引っかからないよう少し待つ (任意)
            # sleep 1 
          done